# site settings
title: Natalie Rothfels
description: Musings on learning, teaching, and building
email: nrothfels@gmail.com
markdown: kramdown
baseurl: ""
url: "https://nrothfels.github.io"

# social
twitter_username: natatouille
github_username: nrothfels

permalink: /blog/:year/:month/:day/:title
